default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 
development:
  <<: *default
  database: love
  username: postgres
  password: gman1


test:
  <<: *default
  database: love
  username: postgres
  password: gman1

production:
  <<: *default
  database: love
  username: postgres
  password: gman1